const Blogs = [
    {
        id: 1,
        title: "How to Build a Fast WordPress Website in 2024",
        slug: "how-to-build-a-fast-wordpress-website-in-2024",
        category: "WordPress",
        date: "March 12, 2024",
        image: "/images/imgi_65_2-2.jpg",
        excerpt: "A practical guide to improving page speed, reducing plugin bloat, and keeping your site lean for better conversions.",
        content: "<p>A fast WordPress website starts with clean hosting, optimized images, and a lightweight theme.</p><h2>What to improve first</h2><p>Audit plugins, compress assets, enable caching, and keep the page structure simple. These changes make the site easier to use and better for conversions.</p>",
        link: "#",
    },
    {
        id: 2,
        title: "Top 10 Shopify Tips to Boost Your Ecommerce Sales",
        slug: "top-10-shopify-tips-to-boost-your-ecommerce-sales",
        category: "Ecommerce",
        date: "April 5, 2024",
        image: "/images/imgi_64_3-2.jpg",
        excerpt: "A focused checklist for stronger product pages, smarter checkout flows, and better customer retention.",
        content: "<p>Shopify stores perform better when product pages answer questions quickly and make checkout feel effortless.</p><h2>Conversion checklist</h2><p>Use clear images, benefit-led descriptions, simple shipping information, and visible trust signals near the buy button.</p>",
        link: "#",
    },
    {
        id: 3,
        title: "React vs Next.js - Which One Should You Choose?",
        slug: "react-vs-next-js-which-one-should-you-choose",
        category: "Development",
        date: "April 18, 2024",
        image: "/images/imgi_66_1-2.jpg",
        excerpt: "Compare performance, SEO, routing, and developer experience so you can choose the right framework for your project.",
        content: "<p>React gives flexibility for interfaces, while Next.js adds routing, rendering choices, and production-friendly conventions.</p><h2>How to decide</h2><p>Choose based on SEO, content needs, app complexity, and deployment workflow rather than popularity alone.</p>",
        link: "#",
    },
    {
        id: 4,
        title: "UI/UX Design Principles Every Developer Should Know",
        slug: "ui-ux-design-principles-every-developer-should-know",
        category: "Design",
        date: "May 2, 2024",
        image: "/images/imgi_66_1-2.jpg",
        excerpt: "Learn how subtle spacing, hierarchy, and visual rhythm improve usability and make your interfaces feel premium.",
        content: "<p>Good UI/UX is built from readable hierarchy, consistent spacing, clear states, and flows that match user intent.</p><h2>Design habits</h2><p>Use fewer competing styles, make important actions visible, and test layouts on mobile before polishing details.</p>",
        link: "#",
    },
    {
        id: 5,
        title: "How to Get Your First Client on Fiverr & Upwork",
        slug: "how-to-get-your-first-client-on-fiverr-and-upwork",
        category: "Freelancing",
        date: "May 14, 2024",
        image: "/images/imgi_64_3-2.jpg",
        excerpt: "Practical steps to positioning your services, writing better proposals, and building trust with early clients.",
        content: "<p>Your first freelance client usually comes from a clear offer, relevant samples, and messages that solve a real problem.</p><h2>Build trust early</h2><p>Show specific results, respond clearly, and make it easy for the client to understand what they will receive.</p>",
        link: "#",
    },
    {
        id: 6,
        title: "WooCommerce vs Shopify - A Complete Comparison",
        slug: "woocommerce-vs-shopify-a-complete-comparison",
        category: "Ecommerce",
        date: "May 22, 2024",
        image: "/images/imgi_65_2-2.jpg",
        excerpt: "A side-by-side breakdown of flexibility, ease of use, and long-term growth so you can choose the right platform.",
        content: "<p>WooCommerce gives more ownership and customization, while Shopify keeps setup and maintenance simpler.</p><h2>Best fit</h2><p>Pick WooCommerce for flexibility and content-heavy stores; pick Shopify when speed, hosting, and simpler operations matter most.</p>",
        link: "#",
    },
];

export { Blogs };
